export global TorrentTableGeometry {
	in-out property <length> minimum-name-width: 180px;
	in-out property <length> size-width: 90px;
	in-out property <length> progress-width: 110px;
	in-out property <length> status-width: 120px;
	in-out property <length> count-width: 58px;
	in-out property <length> rate-width: 94px;
	in-out property <length> eta-width: 74px;
	in-out property <length> actions-width: 116px;
	in-out property <length> quick-action-width: 72px;
	in-out property <length> overflow-action-width: 38px;
}
